
CREATE DATABASE IF NOT EXISTS CFA102G1;

use CFA102G1;

DROP TABLE IF EXISTS COUPON_LIST;
DROP TABLE IF EXISTS COUPON_INFORMATION;
DROP TABLE IF EXISTS APPRAISAL_CASE_IMAGES;
DROP TABLE IF EXISTS APPRAISAL_CASE;
DROP TABLE IF EXISTS APPRAISAL_CLASS;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE `MEMBER` (
  `MEM_NO` int NOT NULL AUTO_INCREMENT COMMENT '會員編號',
  `MEM_NAME` char(20) DEFAULT NULL COMMENT '會員姓名',
  `MEM_GENDER` char(10) DEFAULT NULL COMMENT '會員性別',
  `MEM_PHONE` int DEFAULT NULL COMMENT '會員電話',
  `MEM_EMAIL` varchar(65) DEFAULT NULL COMMENT '會員信箱',
  `MEM_ADDRESS` varchar(65) DEFAULT NULL COMMENT '會員地址',
  `MEM_ACCOUNT` char(20) DEFAULT NULL COMMENT '會員帳號',
  `MEM_PASSWORD` char(20) DEFAULT NULL COMMENT '會員密碼',
  `MEM_BIRTH` char(20) DEFAULT NULL COMMENT '會員生日',
  `MEM_STA` varchar(20) DEFAULT NULL COMMENT '會員狀態',
  PRIMARY KEY (`MEM_NO`)
) COMMENT='會員';

INSERT INTO `CFA102G1`.`MEMBER` (`MEM_NAME`, `MEM_GENDER`, `MEM_PHONE`, `MEM_EMAIL`, `MEM_ADDRESS`, `MEM_ACCOUNT`, `MEM_PASSWORD`, `MEM_BIRTH`, `MEM_STA`) VALUES ('LIN', '男', '0987654321', '@yahoo.com', '台北', 'qwe123', 'qqq123', '2021-01-02', '正常');
INSERT INTO `CFA102G1`.`MEMBER` (`MEM_NAME`, `MEM_GENDER`, `MEM_PHONE`, `MEM_EMAIL`, `MEM_ADDRESS`, `MEM_ACCOUNT`, `MEM_PASSWORD`, `MEM_BIRTH`, `MEM_STA`) VALUES ('CHEN', '男', '0987654312', '@yahoo.com', '桃園', 'qwe987', 'qqq123', '2021-01-02', '正常');
INSERT INTO `CFA102G1`.`MEMBER` (`MEM_NAME`, `MEM_GENDER`, `MEM_PHONE`, `MEM_EMAIL`, `MEM_ADDRESS`, `MEM_ACCOUNT`, `MEM_PASSWORD`, `MEM_BIRTH`, `MEM_STA`) VALUES ('NANA', '女', '0987654312', '@yahoo.com', '新北', 'qwe654', 'qqq123', '2021-01-02', '正常');
INSERT INTO `CFA102G1`.`MEMBER` (`MEM_NAME`, `MEM_GENDER`, `MEM_PHONE`, `MEM_EMAIL`, `MEM_ADDRESS`, `MEM_ACCOUNT`, `MEM_PASSWORD`, `MEM_BIRTH`, `MEM_STA`) VALUES ('AELLN', '男', '0987654321', '@yahoo.com', '台北', 'qwe123', 'qqq123', '2021-01-02', '正常');
INSERT INTO `CFA102G1`.`MEMBER` (`MEM_NAME`, `MEM_GENDER`, `MEM_PHONE`, `MEM_EMAIL`, `MEM_ADDRESS`, `MEM_ACCOUNT`, `MEM_PASSWORD`, `MEM_BIRTH`, `MEM_STA`) VALUES ('ARMIN', '男', '0987654312', '@yahoo.com', '桃園', 'qwe987', 'qqq123', '2021-01-02', '正常');
INSERT INTO `CFA102G1`.`MEMBER` (`MEM_NAME`, `MEM_GENDER`, `MEM_PHONE`, `MEM_EMAIL`, `MEM_ADDRESS`, `MEM_ACCOUNT`, `MEM_PASSWORD`, `MEM_BIRTH`, `MEM_STA`) VALUES ('MIKASA', '女', '0987654312', '@yahoo.com', '新北', 'qwe654', 'qqq123', '2021-01-02', '正常');

CREATE TABLE `APPRAISAL_CLASS` (
  `ACL_NO` int NOT NULL AUTO_INCREMENT COMMENT '估價類別編號',
  `ACL_ID` varchar(100) DEFAULT NULL COMMENT '估價類別名稱',
  PRIMARY KEY (`ACL_NO`)
)COMMENT='估價類別';

INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('電腦');
INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('筆電');
INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('螢幕');
INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('零件');
INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('鍵盤滑鼠類');
INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('音響喇叭');
INSERT INTO `CFA102G1`.`APPRAISAL_CLASS` (`ACL_ID`) VALUES ('其他');

CREATE TABLE `APPRAISAL_CASE` (
  `ACA_NO` int NOT NULL AUTO_INCREMENT COMMENT '估價案件編號',
  `MEM_NO` int NOT NULL COMMENT '會員編號',
  `ACA_ITM_ID` char(100) DEFAULT NULL COMMENT '估價商品名稱',
  `ACL_NO` int NOT NULL COMMENT '估價類別編號',
  `ACA_ITM_SPEC` varchar(1000) DEFAULT NULL COMMENT '估價商品內容(規格)',
  `ACA_DATE` datetime NOT NULL COMMENT '案件日期',
  `ACA_ITM_MODE` varchar(20) NOT NULL COMMENT '案件狀態',
  `ACA_FIRST_P` int DEFAULT NULL COMMENT '報價',
  `ACA_RECPT_DATE` datetime DEFAULT NULL COMMENT '門市收貨日期',
  `ACA_FINAL_P` int DEFAULT NULL COMMENT '成交價',
  `ACA_SHIPMENT_DATE` datetime DEFAULT NULL COMMENT '出貨日期',
  `ACA_PICKUP_DATE` datetime DEFAULT NULL COMMENT '取貨日期',
  `ACA_PAY` char(20) DEFAULT NULL COMMENT '付款方式',
  `ACA_COMP_DATE` datetime DEFAULT NULL COMMENT '完成日期',
  `ACA_COD` char(20) DEFAULT NULL COMMENT '運送方式',
  `ACA_ADRS` varchar(100) DEFAULT NULL COMMENT '配送地址',
  PRIMARY KEY (`ACA_NO`)
)COMMENT='估價案件';

INSERT INTO `CFA102G1`.`APPRAISAL_CASE` (`MEM_NO`, `ACA_ITM_ID`, `ACL_NO`, `ACA_ITM_SPEC`, `ACA_DATE`, `ACA_ITM_MODE`, `ACA_FIRST_P`) VALUES ('1', '筆電', '2', '9成新', '2022-08-23 23:00:00', '提供報價', '11000');
INSERT INTO `CFA102G1`.`APPRAISAL_CASE` (`MEM_NO`, `ACA_ITM_ID`, `ACL_NO`, `ACA_ITM_SPEC`, `ACA_DATE`, `ACA_ITM_MODE`, `ACA_FIRST_P`, `ACA_RECPT_DATE`, `ACA_FINAL_P`, `ACA_PAY`, `ACA_COMP_DATE`, `ACA_COD`, `ACA_ADRS`) VALUES ('2', '螢幕', '3', '9成新', '2022-08-23 23:00:00', '提供成交價', '1200', '2022-08-23 23:00:00', '1000', '現金', '2022-08-26 23:00:00', '宅配', '320桃園市中壢區復興路46號9樓');
INSERT INTO `CFA102G1`.`APPRAISAL_CASE` (`MEM_NO`, `ACA_ITM_ID`, `ACL_NO`, `ACA_ITM_SPEC`, `ACA_DATE`, `ACA_ITM_MODE`, `ACA_FIRST_P`, `ACA_RECPT_DATE`, `ACA_FINAL_P`, `ACA_SHIPMENT_DATE`, `ACA_PICKUP_DATE`, `ACA_COMP_DATE`, `ACA_COD`, `ACA_ADRS`) VALUES ('3', '電腦', '1', '使用1年', '2022-08-23 23:00:00', '取消訂單', '12000', '2022-08-25 23:00:00', '8000', '2022-08-26 23:00:00', '2022-08-28 23:00:00', '2022-08-29 23:00:00', '宅配', '320桃園市中壢區復興路46號9樓');
INSERT INTO `CFA102G1`.`APPRAISAL_CASE` (`MEM_NO`, `ACA_ITM_ID`, `ACL_NO`, `ACA_ITM_SPEC`, `ACA_DATE`, `ACA_ITM_MODE`, `ACA_FIRST_P`) VALUES ('4', '桌機', '1', '使用3年', '2022-08-23 23:00:00', '審核評估', '0');
INSERT INTO `CFA102G1`.`APPRAISAL_CASE` (`MEM_NO`, `ACA_ITM_ID`, `ACL_NO`, `ACA_ITM_SPEC`, `ACA_DATE`, `ACA_ITM_MODE`, `ACA_FIRST_P`) VALUES ('1', '水母喇叭', '5', '9成新', '2022-08-23 23:00:00', '提供報價', '3200');

CREATE TABLE `APPRAISAL_CASE_IMAGES` (
  `ACI_NO` int NOT NULL AUTO_INCREMENT COMMENT '估價案件圖片編號',
  `ACA_NO` int NOT NULL COMMENT '估價案件編號',
  `ACI_IMG` mediumblob COMMENT '估價圖片',
  PRIMARY KEY (`ACI_NO`)
) COMMENT='估價案件圖片';

CREATE TABLE `COUPON_INFORMATION` (
  `CI_NO` int NOT NULL AUTO_INCREMENT COMMENT '優惠劵編號',
  `CI_NAME` char(100) NOT NULL COMMENT '優惠劵名稱',
  `CI_CODE` char(20) NOT NULL COMMENT '編碼',
  `CI_START_TIME` datetime NOT NULL COMMENT '優惠劵開始時間',
  `CI_END_TIME` datetime NOT NULL COMMENT '優惠劵結束時間',
  `DISCOUNT` int NOT NULL COMMENT '折扣',
  `CI_CONTENT` varchar(1000) NOT NULL COMMENT '優惠劵內容',
  PRIMARY KEY (`CI_NO`)
) COMMENT='優惠劵資訊';

INSERT INTO `CFA102G1`.`COUPON_INFORMATION` (`CI_NAME`, `CI_CODE`, `CI_START_TIME`, `CI_END_TIME`, `DISCOUNT`, `CI_CONTENT`) VALUES ('周邊指定品 滿 2690 元現抵 269', 'ABC269', '2021-08-23 00:00:00', '2021-09-01 00:00:00', '269', '商務系列結帳金額滿2690元現抵269折價券(部份商品適用)');
INSERT INTO `CFA102G1`.`COUPON_INFORMATION` (`CI_NAME`, `CI_CODE`, `CI_START_TIME`, `CI_END_TIME`, `DISCOUNT`, `CI_CONTENT`) VALUES ('電競系列滿 3999 折 399', 'SJD399', '2021-08-23 00:00:00', '2021-09-01 00:00:00', '399', '羅技夏日好物祭 電競系列滿3999折399');
INSERT INTO `CFA102G1`.`COUPON_INFORMATION` (`CI_NAME`, `CI_CODE`, `CI_START_TIME`, `CI_END_TIME`, `DISCOUNT`, `CI_CONTENT`) VALUES ('消費結帳滿 5000，即可折抵 400', 'PHAU2G', '2021-08-23 00:00:00', '2021-09-01 00:00:00', '400', '指定類別消費結帳滿$5000元，即可折抵$400元');
INSERT INTO `CFA102G1`.`COUPON_INFORMATION` (`CI_NAME`, `CI_CODE`, `CI_START_TIME`, `CI_END_TIME`, `DISCOUNT`, `CI_CONTENT`) VALUES ('消費結帳滿 2000，即可折抵 200', 'PD200G', '2021-08-23 00:00:00', '2021-09-01 00:00:00', '200', '指定類別消費結帳滿$2000，即可折抵$200');
INSERT INTO `CFA102G1`.`COUPON_INFORMATION` (`CI_NAME`, `CI_CODE`, `CI_START_TIME`, `CI_END_TIME`, `DISCOUNT`, `CI_CONTENT`) VALUES ('消費結帳滿 999，即可折抵 60', 'PHAU2G', '2021-08-23 00:00:00', '2021-09-01 00:00:00', '60', '指定類別消費結帳滿$999，即可折抵$60');
INSERT INTO `CFA102G1`.`COUPON_INFORMATION` (`CI_NAME`, `CI_CODE`, `CI_START_TIME`, `CI_END_TIME`, `DISCOUNT`, `CI_CONTENT`) VALUES ('消費結帳滿 10000，送1000元全聯禮劵', 'PHAU2G', '2021-08-23 00:00:00', '2021-09-01 00:00:00', '0', '指定類別消費結帳滿$10000，送1000元全聯禮劵');

CREATE TABLE `COUPON_LIST` (
  `CI_NO` int NOT NULL COMMENT '優惠劵編號',
  `MEM_NO` int NOT NULL COMMENT '會員編號',
  `CL_STATUS` varchar(45) NOT NULL COMMENT '狀態'
)COMMENT='優惠劵明細';

INSERT INTO `CFA102G1`. `COUPON_LIST` (`CI_NO`,`MEM_NO`,`CL_STATUS`)VALUES('1','1','已使用');
INSERT INTO `CFA102G1`. `COUPON_LIST` (`CI_NO`,`MEM_NO`,`CL_STATUS`)VALUES('2','2','已使用');
INSERT INTO `CFA102G1`. `COUPON_LIST` (`CI_NO`,`MEM_NO`,`CL_STATUS`)VALUES('1','2','未使用');
INSERT INTO `CFA102G1`. `COUPON_LIST` (`CI_NO`,`MEM_NO`,`CL_STATUS`)VALUES('1','3','未使用');
INSERT INTO `CFA102G1`. `COUPON_LIST` (`CI_NO`,`MEM_NO`,`CL_STATUS`)VALUES('1','5','未使用');
INSERT INTO `CFA102G1`. `COUPON_LIST` (`CI_NO`,`MEM_NO`,`CL_STATUS`)VALUES('1','4','已使用');


ALTER TABLE `CFA102G1`.`APPRAISAL_CASE` ADD CONSTRAINT `FK_APPRAISAL_CASE_MEM_NO` FOREIGN KEY (`MEM_NO`) REFERENCES `CFA102G1`.`MEMBER` (`MEM_NO`);
ALTER TABLE `CFA102G1`.`APPRAISAL_CASE` ADD CONSTRAINT `FK_APPRAISAL_CASE_ACL_NO`  FOREIGN KEY (`ACL_NO`) REFERENCES `CFA102G1`.`APPRAISAL_CLASS` (`ACL_NO`);
ALTER TABLE `CFA102G1`.`APPRAISAL_CASE_IMAGES` ADD CONSTRAINT `FK_APPRAISAL_CASE_IMAGES_ACA_NO` FOREIGN KEY (`ACA_NO`) REFERENCES `CFA102G1`.`APPRAISAL_CASE` (`ACA_NO`);
ALTER TABLE `CFA102G1`.`COUPON_LIST` ADD CONSTRAINT `FK_COUPON_LIST_CI_NO` FOREIGN KEY (`CI_NO`)REFERENCES `CFA102G1`.`COUPON_INFORMATION` (`CI_NO`);
ALTER TABLE `CFA102G1`.`COUPON_LIST` ADD CONSTRAINT `FK_COUPON_LIST_MEM_NO`  FOREIGN KEY (`MEM_NO`)REFERENCES `CFA102G1`.`MEMBER` (`MEM_NO`);